# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aebca545b74b43b639fe795eca94da5fac9fad604003d331202e1ff9d73b0d48c8894277f30d3c850dcc009682c35074364131d2d4a485b1fed1930d9cd6baf1

test:
  secret_key_base: 06a7c8b2fead94804cf73246af114db951e0a31168dbb42aa6d2108a6a2653bf550104413de52806b2d3e08ee006a3b8ae8bf3f5b2b9fbf2a6601b3400953a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
